# Generated by Django 3.2 on 2022-11-24 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('answer', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('use_model', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, null=True)),
                ('version', models.CharField(max_length=100)),
                ('file_upload', models.FileField(blank=True, upload_to='upload_model/')),
                ('is_selected', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
