# Generated by Django 3.2 on 2022-11-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0009_alter_aimodel_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='upload_model/'),
        ),
    ]
